### ISSUE TITLE
Live support?

### ISSUE THREAD

**Issue by titpetric** [WowzaMediaSystems/wse-plugin-mediacachelocalcontent#1]
From what I'm reading this only enables local cache for vod applications?

I have a scenario where I want to use mediacache S3 backed scheduled streams and multibitrate stream to bind them together.

I create the usual streamschedule.smil with the schedules for mp4:amazons3/... resources. This works fine. But as I have multiple bitrates, I need to create an additional smil file with <switch> and would like to load it locally from wowza.

```
<smil>
        <head></head>
        <body>
                <switch>
                <video src="140e8524014871621dd046df7d7f5805_500" system-bitrate="500000"></video>
                <video src="140e8524014871621dd046df7d7f5805_1500" system-bitrate="1500000"></video>
                </switch>
        </body>
</smil>
```

Now, I would like to load this smil file from the content/ folder in Wowza, referencing it with `smil:140e8524014871621dd046df7d7f5805.smil`.

If I try to use mediacachelocalcontent to serve this file I get errors in this form:

```
MediaReaderH264.open[1]: java.io.IOException: MediaCacheRandomAccessReader.open: MediaCache source not permitted for this application [amazons3]: amazons3/[redacted]: java.io.IOException: MediaCacheRandomAccessReader.open: MediaCache source not permitted for this application [amazons3]: amazons3/[redacted]|at com.wowza.wms.mediacache.impl.MediaCacheRandomAccessReaderFilter.open(MediaCacheRandomAccessReaderFilter.java:77)|at com.wowza.wms.plugin.RandomAccessReaderMediaCacheLocalContent.open(RandomAccessReaderMediaCacheLocalContent.java:78)|at com.wowza.wms.mediareader.h264.MediaReaderH264.open(MediaReaderH264.java:259)|at com.wowza.wms.stream.publish.PublishingProviderMediaReader.a(PublishingProviderMediaReader.java:239)|at com.wowza.wms.stream.publish.PublishingProviderMediaReader.<init>(PublishingProviderMediaReader.java:97)|
```

If I don't use mediacachelocalcontent and use the default `com.wowza.wms.mediacache.impl.MediaCacheRandomAccessReader`

```
WARN    server  comment 2016-09-10      08:34:15        -       -       -       -       -       4.872   -       -       -       -       -       -       -       -       MediaCache.createNewCachItem: Cannot find MediaCacheSource for (140e8
524014871621dd046df7d7f5805.smil).
WARN    server  comment 2016-09-10      08:34:15        -       -       -       -       -       4.873   -       -       -       -       -       -       -       -       MediaCache.createNewCachItem: Cannot find MediaCacheSource for (140e8
524014871621dd046df7d7f5805.smil).
WARN    server  comment 2016-09-10      08:34:15        -       -       -       -       -       4.873   -       -       -       -       -       -       -       140e8524014871621dd046df7d7f5805.smil   open: java.io.IOException: MediaCache
RandomAccessReader.open: Item not in cache: 140e8524014871621dd046df7d7f5805.smil
WARN    server  comment 2016-09-10      08:34:15        -       -       -       -       -       4.873   -       -       -       -       -       -       -       -       HTTPStreamerSanJoseLiveIndex.indexPlaylist[ams/_definst_/smil:140e852
4014871621dd046df7d7f5805.smil]: MediaList is empty.
```

What can I do to resolve these issues?

**Comment by rogerlittin** [comment]
I think the reason you're getting this error is because you need to specify which Media Cache sources are allowed to be used by the application. This is a new feature with Wowza Streaming Engine and is automatically done when you create a new VOD-Edge application. If you create a different application that uses Media Cache then you need to specify the sources your self.

You can do this by editing the Application.xml and setting the sources in the `MediaCacheSourceList` setting.

```
        <MediaCache>
            <MediaCacheSourceList>*</MediaCacheSourceList>
        </MediaCache>
```

This is a comma separated list with \* as a wildcard.

**Comment by titpetric** [comment]
It was exactly this, it was empty and I'm doing a live app. Was just going to post that i added 'amazons3' into this value. Thank you!
